services:
  - type: web
    name: fullstack-backend
    env: python
    buildCommand: |
      cd backend-api
      pip install -r requirements.txt
    startCommand: |
      cd backend-api
      python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false 